target 'ForexLessons' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'Fabric'
  pod 'Crashlytics'

  pod 'Firebase/Messaging'
  pod 'Google/SignIn'

  pod 'Lock', '~> 1.29'
  pod 'Lock/TouchID'
  pod 'Lock/SMS'
  pod 'Lock/Email'
  pod 'Lock/Safari'

end
