target 'ForexLessons' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'Fabric'
  pod 'Crashlytics'

  pod 'Firebase/Messaging'
  pod 'Google/SignIn'

end
